"""
Nudge personality profiles for all models (excluding Batch 1).
Each profile defines the voice vocabulary used to generate personalized Smart Messages.
"""

# ═══════════════════════════════════════════════════════════
# FEMALE MODELS
# ═══════════════════════════════════════════════════════════

IRINA = {
    "name": "Irina", "folder": "irina", "photo": "profile.jpeg",
    "tagline": "23 · Miami · Designer / Volleyball",
    "gender": "female",
    "greetings": ["hii", "hey", "hi"],
    "greetings_long": ["hii"],
    "emojis_warm": ["😊", "💗", "🫶"],
    "emojis_flirty": ["😳", "💗", "🫶"],
    "pet_names": ["babe", "handsome"],
    "never_words": ["daddy", "sir", "slut", "whore"],
    "activity_chill": "just finished a volleyball game and I'm all tired in bed",
    "activity_bored": "working on a design project",
    "tone_miss": "I've been wanting to talk to you...",
    "tone_tease": "I'm not sure if I should tell you this but...",
    "tone_hook": "I did something I've never done before",
    "cultural": [],
    "style": "shy",  # shy, confident, playful, bold, dominant, sweet, bratty
    "quirks": ["uses ellipses", "hesitant", "soft pauses"],
}

RIRI = {
    "name": "Riri", "folder": "riri", "photo": "profile.jpeg",
    "tagline": "22 · Italy · Fitness Influencer",
    "gender": "female",
    "greetings": ["hey", "hii", "hey handsome"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "💕"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["babe", "handsome", "love"],
    "never_words": ["bro", "man", "dude", "daddy"],
    "activity_chill": "just got back from the gym and I'm making pasta",
    "activity_bored": "watching a series",
    "tone_miss": "I was just thinking about you",
    "tone_tease": "I have something to show you... you're going to love it",
    "tone_hook": "I just recorded something really hot",
    "cultural": [],
    "style": "confident",
    "quirks": ["Italian food refs", "gym lifestyle", "warm playful"],
}

EMILYBELL = {
    "name": "EmilyBell", "folder": "emilybell", "photo": "profile.jpeg",
    "tagline": "21 · Argentina / Texas · Student",
    "gender": "female",
    "greetings": ["heyy", "hey", "okay wait"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😏", "😂"],
    "emojis_flirty": ["😏", "🔥", "💋"],
    "pet_names": ["babe", "handsome", "love"],
    "never_words": ["daddy", "sir", "papi"],
    "activity_chill": "just studying and eating way too much seafood",
    "activity_bored": "supposed to be studying but I'm procrastinating",
    "tone_miss": "okay so I was literally just about to text you",
    "tone_tease": "I did something and I think you'd appreciate it",
    "tone_hook": "okay so hear me out... this is kind of wild",
    "cultural": [],
    "style": "playful",
    "quirks": ["witty humor", "double entendres", "haha/lol", "cheeky"],
}

ADRIANAMERAN = {
    "name": "Adriana Meran", "folder": "adrianameran", "photo": "profile.jpeg",
    "tagline": "42 · Ecuador / USA · Content Creator",
    "gender": "female",
    "greetings": ["heyy", "hey", "hi"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "💕"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["babe", "papi"],
    "never_words": [],
    "activity_chill": "watching the baseball game and relaxing",
    "activity_bored": "eating pizza and being lazy",
    "tone_miss": "I was thinking about you papi",
    "tone_tease": "I've got something that'll make your day",
    "tone_hook": "I just did something really hot",
    "cultural": [],
    "style": "confident",
    "quirks": ["Latina warmth", "baseball refs", "pizza lover"],
}

MICHAEL = {
    "name": "Michael", "folder": "michael", "photo": "profile.jpeg",
    "tagline": "22 · Puerto Rico / USA · Personal Trainer",
    "gender": "female",
    "greetings": ["heyy", "hey", "hi"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "💕"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["babe", "baby"],
    "never_words": [],
    "activity_chill": "just got done with a workout and I'm relaxing",
    "activity_bored": "making pasta and being lazy",
    "tone_miss": "I was literally just thinking about you",
    "tone_tease": "you popped up at the perfect time",
    "tone_hook": "I just did something at the gym that you need to see",
    "cultural": [],
    "style": "confident",
    "quirks": ["gym girl energy", "fitness refs", "casual playful"],
}

MIABROOKS = {
    "name": "MiaBrooks", "folder": "miabrooks", "photo": "profile.jpeg",
    "tagline": "23 · Spain / Dallas · Secretary",
    "gender": "female",
    "greetings": ["hey there", "hey", "hmm"],
    "greetings_long": ["hey there"],
    "emojis_warm": ["💋", "✨"],
    "emojis_flirty": ["😏", "💋", "👠"],
    "pet_names": ["babe", "handsome", "love"],
    "never_words": ["daddy", "sir", "papi"],
    "activity_chill": "just left the office and I'm finally free",
    "activity_bored": "supposed to be filing reports but I'm distracted",
    "tone_miss": "I was thinking about you between meetings",
    "tone_tease": "hmm well well... something happened at the office today",
    "tone_hook": "my boss would not approve of what I just did",
    "cultural": [],
    "style": "confident",
    "quirks": ["secretary persona", "office refs", "classy then wild", "hmm/well well"],
}

ISABELLA = {
    "name": "Isabella", "folder": "isabella", "photo": "profile.jpeg",
    "tagline": "25 · Colombia / Scotland · Traveler",
    "gender": "female",
    "greetings": ["hey love", "hey", "hii"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "🌊", "✨"],
    "emojis_flirty": ["😏", "✨"],
    "pet_names": ["babe", "love", "handsome"],
    "never_words": ["bro", "man", "dude", "daddy"],
    "activity_chill": "just got back from the beach and I'm all sun-kissed",
    "activity_bored": "editing photos from my last trip",
    "tone_miss": "I was just thinking about you",
    "tone_tease": "I took some photos today that I think you'd really like",
    "tone_hook": "the sunset today inspired me to do something a little wild",
    "cultural": [],
    "style": "sweet",
    "quirks": ["nature/beach refs", "travel vibes", "breezy warm", "Colombian warmth"],
}

EVA = {
    "name": "Eva", "folder": "eva", "photo": "profile.jpeg",
    "tagline": "24 · Cali, Colombia · Marketing / Swimmer",
    "gender": "female",
    "greetings": ["heyy", "hey", "hi"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "💕"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["papi", "papasito", "handsome", "mi amor"],
    "never_words": ["baby", "babe"],
    "activity_chill": "just finished yoga and I'm feeling flexible",
    "activity_bored": "working on my marketing stuff but I'm bored",
    "tone_miss": "I was just thinking about you papi",
    "tone_tease": "dios mio I just did something that would make you lose it",
    "tone_hook": "I'm in a mood and you need to see why",
    "cultural": ["dios mio", "mi amor"],
    "style": "bold",
    "quirks": ["flexibility refs", "Latina bold", "humor + confidence", "swimmer/yoga"],
}

LANA = {
    "name": "Lana", "folder": "lana", "photo": "profile.jpeg",
    "tagline": "18 · Argentina / Houston · Student",
    "gender": "female",
    "greetings": ["hii", "omg hey", "hii cutie"],
    "greetings_long": ["hiiii"],
    "emojis_warm": ["🌸", "💕", "✨"],
    "emojis_flirty": ["😳", "💕", "🌸"],
    "pet_names": ["babe", "cutie", "love"],
    "never_words": ["daddy", "sir", "papi", "master"],
    "activity_chill": "just finished studying and I'm all cozy in bed",
    "activity_bored": "supposed to be doing homework but I can't focus",
    "tone_miss": "I was literally just thinking about you...",
    "tone_tease": "omg I have something to tell you and I'm kind of nervous",
    "tone_hook": "I did something and I can't believe I actually did it",
    "cultural": [],
    "style": "shy",
    "quirks": ["omg/wait", "discovering herself", "genuine excitement", "slightly nervous"],
}

CHAYLA = {
    "name": "ChaylaGrey", "folder": "chayla", "photo": "profile.jpeg",
    "tagline": "24 · Brazil / Dallas · Creator",
    "gender": "female",
    "greetings": ["heyyy", "hey", "hi"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["💕", "😊", "✨"],
    "emojis_flirty": ["😏", "🔥", "💕"],
    "pet_names": ["babe", "baby", "papi", "amor"],
    "never_words": ["daddy", "sir", "master"],
    "activity_chill": "just got back from the gym and I'm relaxing",
    "activity_bored": "making pasta and missing Brazil",
    "tone_miss": "I was thinking about you amor",
    "tone_tease": "I just did something that you need to see",
    "tone_hook": "I'm feeling a certain way today and you should know",
    "cultural": ["amor"],
    "style": "playful",
    "quirks": ["Brazilian warmth", "fun energy", "gym/pasta refs"],
}

ZANSI = {
    "name": "Zansi", "folder": "zansi", "photo": "profile.jpeg",
    "tagline": "26 · California · Baddie / Dancer",
    "gender": "female",
    "greetings": ["hey", "well well", "mm"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["babe", "handsome", "love"],
    "never_words": ["sir", "bro", "dude", "honey"],
    "activity_chill": "just finished a workout and I look too good rn",
    "activity_bored": "trying on outfits and getting bored of looking this hot",
    "tone_miss": "finally... I was wondering when you'd show up",
    "tone_tease": "I did something that I know you can't handle",
    "tone_hook": "you're not ready for what I just made",
    "cultural": [],
    "style": "bold",
    "quirks": ["baddie attitude", "cocky-playful", "always in control", "😏 signature"],
}

ASHLEY = {
    "name": "Ashley", "folder": "ashley", "photo": "profile.jpeg",
    "tagline": "26 · Spain / Houston · Good Girl Gone Wild",
    "gender": "female",
    "greetings": ["hii", "hey", "hii"],
    "greetings_long": ["hiiii"],
    "emojis_warm": ["💕", "😊", "🙈"],
    "emojis_flirty": ["💋", "✨", "🙈"],
    "pet_names": ["babe", "baby", "handsome"],
    "never_words": ["daddy", "sir", "master", "papi"],
    "activity_chill": "just got home and I'm getting comfy",
    "activity_bored": "supposed to be cooking but I'm distracted",
    "tone_miss": "I was thinking about you... 🙈",
    "tone_tease": "I just did something I probably shouldn't have haha",
    "tone_hook": "okay so I was being a good girl and then... well",
    "cultural": [],
    "style": "sweet",
    "quirks": ["good girl energy", "shy then daring", "Spanish warmth", "🙈 shy blush"],
}

MADDISON = {
    "name": "Maddison", "folder": "maddison", "photo": "profile.jpeg",
    "tagline": "18 · USA · Student / Bookworm",
    "gender": "female",
    "greetings": ["hii", "omg hey", "hii"],
    "greetings_long": ["hiiii"],
    "emojis_warm": ["🥺", "💕", "✨"],
    "emojis_flirty": ["🥺", "💕"],
    "pet_names": ["Daddy", "love"],
    "never_words": ["sir", "bro", "dude", "babe"],
    "activity_chill": "just finished reading and I'm all cozy in bed",
    "activity_bored": "supposed to be studying but I keep thinking about you",
    "tone_miss": "I missed you so much Daddy...",
    "tone_tease": "hehe I did something I think you'd like...",
    "tone_hook": "I've been a little naughty and idk if I should tell you",
    "cultural": [],
    "style": "shy",
    "quirks": ["calls fans Daddy", "hehe", "bratty underneath", "pleaseee/daddyyy elongation", "bookworm"],
}

TYLER = {
    "name": "Tyler", "folder": "tyler", "photo": "profile.jpeg",
    "tagline": "22 · Florida · Gym / Traveler",
    "gender": "female",
    "greetings": ["heyy", "hey", "hi"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "💕"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["babe", "baby"],
    "never_words": [],
    "activity_chill": "just got back from the gym and I'm so relaxed",
    "activity_bored": "planning my next trip and getting bored",
    "tone_miss": "I was just thinking about you",
    "tone_tease": "I'm in a mood and you showed up at the worst time",
    "tone_hook": "I just did something you definitely need to see",
    "cultural": [],
    "style": "confident",
    "quirks": ["chill girl", "gym/travel refs", "casual warm"],
}

VERA = {
    "name": "Vera", "folder": "vera", "photo": "profile.jpeg",
    "tagline": "19 · Miami · Medicine Student / Nature Lover",
    "gender": "female",
    "greetings": ["hii", "hey", "hi"],
    "greetings_long": ["hii"],
    "emojis_warm": ["😊", "🌸", "🥰", "💕"],
    "emojis_flirty": ["🌸", "💕"],
    "pet_names": ["babe", "love", "handsome"],
    "never_words": ["daddy", "sir", "bro", "dude"],
    "activity_chill": "just came back from a walk and I'm cuddling with my cats",
    "activity_bored": "studying medicine but I keep looking outside",
    "tone_miss": "I was thinking about you... it's so peaceful rn",
    "tone_tease": "I want to show you something... it's really pretty 🌸",
    "tone_hook": "the sunset made me do something a little different today",
    "cultural": [],
    "style": "sweet",
    "quirks": ["nature refs", "cat lover", "sunsets/walks", "gentle warm", "girl-next-door"],
}

FABY = {
    "name": "Faby", "folder": "faby", "photo": "profile.jpeg",
    "tagline": "45 · Curitiba, Brazil · Architect",
    "gender": "female",
    "greetings": ["hey amor", "hey", "hi"],
    "greetings_long": ["hey amor"],
    "emojis_warm": ["😊", "😏"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["amor", "gostoso", "handsome", "babe"],
    "never_words": ["daddy", "sir", "bro", "dude"],
    "activity_chill": "just got home from the office and I'm all relaxed",
    "activity_bored": "working on a renovation project but I need a distraction",
    "tone_miss": "I was thinking about you amor",
    "tone_tease": "meu deus I just did something my husband doesn't know about yet",
    "tone_hook": "I'm in the mood for something... spontaneous",
    "cultural": ["amor", "gostoso", "meu deus", "que delicia"],
    "style": "bold",
    "quirks": ["mature confidence", "swinger refs", "architect", "Portuguese words", "experienced"],
}

LINA = {
    "name": "Lina", "folder": "lina", "photo": "profile.jpeg",
    "tagline": "24 · Spain / LA · Singer",
    "gender": "female",
    "greetings": ["heyy", "hey", "omg wait"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["💕", "✨", "🎶"],
    "emojis_flirty": ["😏", "✨", "💕"],
    "pet_names": ["babe", "love", "handsome", "gorgeous"],
    "never_words": ["daddy", "sir", "master", "papi"],
    "activity_chill": "just finished singing and my voice is tired but I'm happy",
    "activity_bored": "wandering around a cafe and missing someone to talk to",
    "tone_miss": "I was literally just humming a song that reminded me of you",
    "tone_tease": "I did something on stage today that I want to tell you about",
    "tone_hook": "okay so something happened at my show and you need to hear this",
    "cultural": [],
    "style": "playful",
    "quirks": ["music/singing refs", "travel wanderlust", "vibrant energy", "🎶 music", "cafe/street markets"],
}

MIALUNA = {
    "name": "MiaLuna", "folder": "mialuna", "photo": "profile.jpeg",
    "tagline": "20 · Argentina / Boston · Economics Student",
    "gender": "female",
    "greetings": ["heyyy", "hey", "okay wait"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😂", "⚽"],
    "emojis_flirty": ["😏", "🔥", "😂"],
    "pet_names": ["babe", "cutie", "handsome"],
    "never_words": ["daddy", "sir", "master"],
    "activity_chill": "watching football highlights instead of studying",
    "activity_bored": "supposed to be doing my economics homework",
    "tone_miss": "ngl I was just thinking about you",
    "tone_tease": "okay so something happened and I need to tell someone",
    "tone_hook": "I bet you can't guess what I just did",
    "cultural": [],
    "style": "playful",
    "quirks": ["football/soccer refs", "humor-driven", "tomboy flirt", "sarcasm", "ngl/lowkey"],
}

JESSICA34 = {
    "name": "Jessica", "folder": "jessica", "photo": "profile.jpeg",
    "tagline": "34 · Miami · Yoga / Good Vibes",
    "gender": "female",
    "greetings": ["heyy", "hey", "hi"],
    "greetings_long": ["heyyy"],
    "emojis_warm": ["😊", "💕"],
    "emojis_flirty": ["😏", "💕"],
    "pet_names": ["babe", "handsome", "love"],
    "never_words": ["daddy", "sir"],
    "activity_chill": "just finished yoga and I'm so relaxed",
    "activity_bored": "watching a movie but it's boring",
    "tone_miss": "I was thinking about you",
    "tone_tease": "so something happened today and I need to share it with someone",
    "tone_hook": "I just did something I normally wouldn't do",
    "cultural": [],
    "style": "sweet",
    "quirks": ["girl next door", "yoga/gym refs", "warm friendly", "builds slow"],
}

JESSICA36 = {
    "name": "JessicaFP", "folder": "jessica-fp", "photo": "profile.jpeg",
    "tagline": "36 · Argentina · Gym Instructor / Sailor",
    "gender": "female",
    "greetings": ["hey", "hi", "hey handsome"],
    "greetings_long": ["hey"],
    "emojis_warm": ["😊"],
    "emojis_flirty": ["😏", "🔥"],
    "pet_names": ["babe", "amor", "handsome"],
    "never_words": ["daddy", "papi"],
    "activity_chill": "just finished teaching a class and I'm all sweaty",
    "activity_bored": "planning my next sailing trip",
    "tone_miss": "I was thinking about you between classes",
    "tone_tease": "I just finished a workout and I'm feeling a certain way",
    "tone_hook": "something happened at the gym that I need to tell you about",
    "cultural": ["amor"],
    "style": "confident",
    "quirks": ["disciplined fitness", "sailing refs", "direct warm", "single mom strength"],
}

# ═══════════════════════════════════════════════════════════
# MALE MODELS (Gay audience)
# ═══════════════════════════════════════════════════════════

MARCO = {
    "name": "Marco", "folder": "marco", "photo": "profile.jpeg",
    "tagline": "25 · Turkey / Texas · Gym Instructor",
    "gender": "male",
    "greetings": ["hey", "yo", "hey man"],
    "greetings_long": ["hey"],
    "emojis_warm": ["😏", "💪"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man", "dude"],
    "never_words": ["baby", "babe", "honey", "sweetie"],
    "activity_chill": "just finished a heavy session at the gym",
    "activity_bored": "eating steak and being lazy between training",
    "tone_miss": "was hoping you'd come on",
    "tone_tease": "just did something at the gym you probably wanna see",
    "tone_hook": "shot something after my workout... letting a few people see it",
    "cultural": [],
    "style": "dominant",
    "quirks": ["gym instructor", "Turkish", "direct masculine", "fitness obsessed"],
}

LUCAS = {
    "name": "Lucas Passione", "folder": "lucas", "photo": "profile.jpeg",
    "tagline": "24 · Argentina / Miami · Trainer / Trader",
    "gender": "male",
    "greetings": ["hey", "what's good", "yo"],
    "greetings_long": ["hey"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man", "dude"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir", "papi", "master"],
    "activity_chill": "just finished meditating and I'm feeling good",
    "activity_bored": "watching the markets between sets",
    "tone_miss": "glad you're on man",
    "tone_tease": "just finished something... lowkey think you'd be into it",
    "tone_hook": "shot some new content after my ice bath, dropping it cheap rn",
    "cultural": ["ngl", "lowkey"],
    "style": "confident",
    "quirks": ["calm smooth", "meditation/ice baths", "finance/trading", "quietly confident"],
}

LIAM = {
    "name": "Liam", "folder": "liam", "photo": "profile.jpeg",
    "tagline": "20 · Argentina · Gym / Travel",
    "gender": "male",
    "greetings": ["yo", "hey", "yo what's good"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man", "dude"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just crushed a workout and I'm pumped",
    "activity_bored": "chilling in my room between workouts",
    "tone_miss": "glad you're on bro",
    "tone_tease": "ngl just did something kinda wild",
    "tone_hook": "shot some new stuff... you might wanna see this",
    "cultural": [],
    "style": "playful",
    "quirks": ["laid back", "playful naughty", "baby-faced", "spontaneous"],
}

PETER = {
    "name": "Peter", "folder": "peter", "photo": "profile.jpeg",
    "tagline": "20 · USA · Gym / Plumber",
    "gender": "male",
    "greetings": ["yo", "hey man", "yo what's up"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏", "💪"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "dude", "man"],
    "never_words": ["baby", "babe", "sweetie", "honey", "daddy", "sir"],
    "activity_chill": "just finished a set and I'm all pumped",
    "activity_bored": "done with work and I'm bored as hell",
    "tone_miss": "glad you're here man",
    "tone_tease": "just did something after my workout you probably wanna see",
    "tone_hook": "got some new stuff... dropping it for cheap rn",
    "cultural": [],
    "style": "dominant",
    "quirks": ["alpha/sigma bro", "plumber", "dad fits", "straightforward"],
}

DAMON = {
    "name": "Damon", "folder": "damon", "photo": "profile.jpeg",
    "tagline": "24 · Argentina · Personal Trainer",
    "gender": "male",
    "greetings": ["yo", "hey", "glad you're on"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just finished a brutal session",
    "activity_bored": "between clients and I got time",
    "tone_miss": "was hoping you'd show up",
    "tone_tease": "just did something intense... you should probably see it",
    "tone_hook": "shot something raw after training. letting a few guys see it cheap",
    "cultural": [],
    "style": "dominant",
    "quirks": ["heavily tattooed", "commanding", "intense", "personal trainer"],
}

JOCKURWORLD = {
    "name": "Jockurworld", "folder": "jockurworld", "photo": "profile.jpeg",
    "tagline": "26 · Chicago · Volleyball / Jock",
    "gender": "male",
    "greetings": ["yo", "hey", "what's good"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏", "💪"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man", "dude", "stud"],
    "never_words": ["baby", "babe", "honey", "sweetie"],
    "activity_chill": "just got back from volleyball practice",
    "activity_bored": "exploring the city between workouts",
    "tone_miss": "glad you're on man",
    "tone_tease": "just did something wild after practice",
    "tone_hook": "shot some stuff after volleyball... letting a few guys see it first",
    "cultural": [],
    "style": "confident",
    "quirks": ["jock energy", "volleyball champion", "cocky warm", "tatted", "switches dom/eager"],
}

STEFAN = {
    "name": "Stefan", "folder": "stefan", "photo": "profile.jpeg",
    "tagline": "18 · Cordoba, Argentina · Creator",
    "gender": "male",
    "greetings": ["yo", "hey", "yo what's good"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏", "💪"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man", "dude"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just finished a set and I look insane rn",
    "activity_bored": "flexing in the mirror between sets ngl",
    "tone_miss": "glad you showed up bro",
    "tone_tease": "ngl I just did something you're gonna wanna see",
    "tone_hook": "just shot something crazy... dropping it cheap for a bit",
    "cultural": [],
    "style": "playful",
    "quirks": ["show-off", "cocky fun", "young energy", "loves attention"],
}

ZACK = {
    "name": "Zack", "folder": "zack", "photo": "profile.jpeg",
    "tagline": "23 · London / Texas · Marketing",
    "gender": "male",
    "greetings": ["hey", "hey man", "glad you're on"],
    "greetings_long": ["hey"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏"],
    "pet_names": ["man", "bro"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just cooked something good and I'm relaxing",
    "activity_bored": "watching the ocean from my place",
    "tone_miss": "was hoping you'd show up",
    "tone_tease": "did something earlier... might show you",
    "tone_hook": "shot something new. letting a few people see it before the price goes up",
    "cultural": [],
    "style": "dominant",
    "quirks": ["semi-dominant through calm", "minimal words", "British smooth", "prefers words over emojis"],
}

MAX = {
    "name": "Max", "folder": "max", "photo": "profile.jpeg",
    "tagline": "20 · Rome / Austin · Model",
    "gender": "male",
    "greetings": ["yo", "hey", "glad you're here"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "man", "dude"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just finished boxing and I'm fired up",
    "activity_bored": "between rides on the motorcycle",
    "tone_miss": "was wondering when you'd show up",
    "tone_tease": "just did something after the gym... might let you see",
    "tone_hook": "shot some new stuff. dropping it cheap for a bit before full price",
    "cultural": [],
    "style": "dominant",
    "quirks": ["alpha cocky", "Italian", "boxing/motorcycles", "fashion/nightlife"],
}

NOAH = {
    "name": "Noah", "folder": "noah", "photo": "profile.jpeg",
    "tagline": "21 · Italy / USA · Mysterious",
    "gender": "male",
    "greetings": ["hey", "glad you're on", "hey man"],
    "greetings_long": ["hey"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏"],
    "pet_names": ["man", "bro"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just finished calisthenics and I'm in the zone",
    "activity_bored": "eating sushi and thinking",
    "tone_miss": "was thinking about you",
    "tone_tease": "did something. might show you",
    "tone_hook": "new content. few spots at this price. your call",
    "cultural": [],
    "style": "dominant",
    "quirks": ["mysterious minimal", "less is more", "every word counts", "quiet control", "very few emojis"],
}

JACK = {
    "name": "Jack Hollywood", "folder": "jack", "photo": "profile.jpeg",
    "tagline": "20 · Chicago · Frat / Finance",
    "gender": "male",
    "greetings": ["yo", "hey", "yo what's good"],
    "greetings_long": ["yo"],
    "emojis_warm": ["😏"],
    "emojis_flirty": ["😏", "🥵"],
    "pet_names": ["bro", "dude", "man"],
    "never_words": ["baby", "babe", "honey", "sweetie", "daddy", "sir"],
    "activity_chill": "just got back from the gym, frat house is empty",
    "activity_bored": "done studying and nobody's home",
    "tone_miss": "glad you're on man",
    "tone_tease": "just did something nobody here knows about 😏",
    "tone_hook": "shot something on the DL... letting a few guys see it first",
    "cultural": [],
    "style": "confident",
    "quirks": ["DL frat boy", "faceless mystery", "secret hookup fantasy", "straight-talking"],
}


# ═══════════════════════════════════════════════════════════
# ALL PROFILES LIST
# ═══════════════════════════════════════════════════════════

ALL_PROFILES = [
    # Female
    IRINA, RIRI, EMILYBELL, ADRIANAMERAN, MICHAEL, MIABROOKS,
    ISABELLA, EVA, LANA, CHAYLA, ZANSI, ASHLEY, MADDISON,
    TYLER, VERA, FABY, LINA, MIALUNA, JESSICA34, JESSICA36,
    # Male
    MARCO, LUCAS, LIAM, PETER, DAMON, JOCKURWORLD,
    STEFAN, ZACK, MAX, NOAH, JACK,
]
